version: '3'
services:
  web:
    image: denyskozak/the-best-todo-front-end
    ports:
      - "80:80"
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - server
  server:
    image: denyskozak/the-best-todo-back-end
    volumes:
      - "./dockerScripts:/app/dockerScripts"
    ports:
      - "4000:4000"
    restart: always
    entrypoint: ["sh", "./dockerScripts/entrypoint.sh"]
    environment:
      NODE_ENV: production
      PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
      APP_SECRET: ${APP_SECRET}
    depends_on:
      - prisma
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~